"""siamang public API."""

from importlib.metadata import version as _pkg_version

try:
    __version__ = _pkg_version("siamang")
except Exception:
    __version__ = "0.0.0"

from siamang.core import (
    AND,
    NOT,
    OR,
    Block,
    Expression,
    FilterRule,
    LikertScale,
    LintWarning,
    Matrix,
    Media,
    MissingValue,
    MultiChoice,
    NumericInput,
    OpenText,
    Option,
    Page,
    Question,
    Questionnaire,
    Quota,
    Ranking,
    Script,
    SingleChoice,
    ValidationIssue,
    VarRef,
    Variable,
    VariableMap,
    compare,
)
from siamang.data import BannerTable, SurveyData, SurveyTables
from siamang.deploy import DeployResult
from siamang.reporting import (
    BarChart,
    BoxPlot,
    CrossTable,
    FreqTable,
    GroupMeanTable,
    HeatMap,
    ScatterPlot,
)
from siamang.frontend.theme import UIConfig, get_preset
from siamang.io import (
    CSVReader,
    CSVWriter,
    DictionaryReader,
    DictionaryWriter,
    ExcelReader,
    ExcelWriter,
    RScriptWriter,
    SPSSReader,
    SPSSWriter,
    StataReader,
    StataWriter,
    SurveyDataReader,
    read_spss,
    read_stata,
)

__all__ = [
    "__version__",
    "AND",
    "BannerTable",
    "Block",
    "CSVReader",
    "CSVWriter",
    "DeployResult",
    "DictionaryReader",
    "DictionaryWriter",
    "ExcelReader",
    "ExcelWriter",
    "Expression",
    "FilterRule",
    "LikertScale",
    "LintWarning",
    "Matrix",
    "Media",
    "MissingValue",
    "MultiChoice",
    "NOT",
    "NumericInput",
    "OR",
    "OpenText",
    "Option",
    "Page",
    "Question",
    "Questionnaire",
    "Quota",
    "RScriptWriter",
    "Ranking",
    "SPSSReader",
    "SPSSWriter",
    "Script",
    "SingleChoice",
    "StataReader",
    "StataWriter",
    "SurveyData",
    "SurveyDataReader",
    "SurveyTables",
    "ValidationIssue",
    "VarRef",
    "Variable",
    "VariableMap",
    "compare",
    "read_spss",
    "read_stata",
    "UIConfig",
    "get_preset",
    "BarChart",
    "BoxPlot",
    "CrossTable",
    "FreqTable",
    "GroupMeanTable",
    "HeatMap",
    "ScatterPlot",
]
